package com.example.coco.entity;

import java.util.Date;

public class FlywaySchemaHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_rank
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private Integer installedRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.version
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.description
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.type
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.script
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private String script;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.checksum
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private Integer checksum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_by
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private String installedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_on
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private Date installedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.execution_time
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private Integer executionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.success
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    private Boolean success;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_rank
     *
     * @return the value of flyway_schema_history.installed_rank
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public Integer getInstalledRank() {
        return installedRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_rank
     *
     * @param installedRank the value for flyway_schema_history.installed_rank
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.version
     *
     * @return the value of flyway_schema_history.version
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.version
     *
     * @param version the value for flyway_schema_history.version
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.description
     *
     * @return the value of flyway_schema_history.description
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.description
     *
     * @param description the value for flyway_schema_history.description
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.type
     *
     * @return the value of flyway_schema_history.type
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.type
     *
     * @param type the value for flyway_schema_history.type
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.script
     *
     * @return the value of flyway_schema_history.script
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public String getScript() {
        return script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.script
     *
     * @param script the value for flyway_schema_history.script
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setScript(String script) {
        this.script = script == null ? null : script.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.checksum
     *
     * @return the value of flyway_schema_history.checksum
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public Integer getChecksum() {
        return checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.checksum
     *
     * @param checksum the value for flyway_schema_history.checksum
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setChecksum(Integer checksum) {
        this.checksum = checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_by
     *
     * @return the value of flyway_schema_history.installed_by
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public String getInstalledBy() {
        return installedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_by
     *
     * @param installedBy the value for flyway_schema_history.installed_by
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setInstalledBy(String installedBy) {
        this.installedBy = installedBy == null ? null : installedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.installed_on
     *
     * @return the value of flyway_schema_history.installed_on
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public Date getInstalledOn() {
        return installedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.installed_on
     *
     * @param installedOn the value for flyway_schema_history.installed_on
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setInstalledOn(Date installedOn) {
        this.installedOn = installedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.execution_time
     *
     * @return the value of flyway_schema_history.execution_time
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public Integer getExecutionTime() {
        return executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.execution_time
     *
     * @param executionTime the value for flyway_schema_history.execution_time
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flyway_schema_history.success
     *
     * @return the value of flyway_schema_history.success
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flyway_schema_history.success
     *
     * @param success the value for flyway_schema_history.success
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }
}