package com.example.coco.mapper;

import com.example.coco.entity.FlywaySchemaHistory;
import com.example.coco.entity.FlywaySchemaHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    long countByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int deleteByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int insert(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int insertSelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    List<FlywaySchemaHistory> selectByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    FlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int updateByExampleSelective(@Param("record") FlywaySchemaHistory record, @Param("example") FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int updateByExample(@Param("record") FlywaySchemaHistory record, @Param("example") FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int updateByPrimaryKeySelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Wed Oct 26 01:45:57 JST 2022
     */
    int updateByPrimaryKey(FlywaySchemaHistory record);
}