package com.example.coco.mapper;

import com.example.coco.entity.RUserRole;
import com.example.coco.entity.RUserRoleExample;
import com.example.coco.entity.RUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    long countByExample(RUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(RUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insert(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insertSelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    List<RUserRole> selectByExample(RUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    RUserRole selectByPrimaryKey(RUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RUserRole record, @Param("example") RUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RUserRole record, @Param("example") RUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RUserRole record);
}